#ifndef __PRP_LINK_H
#define __PRP_LINK_H

enum {
	IFLA_PRP_UNSPEC,
	IFLA_PRP_SLAVE1,
	IFLA_PRP_SLAVE2,
	IFLA_PRP_SUPADDR,

	__IFLA_PRP_MAX,
};
#define IFLA_PRP_MAX (__IFLA_PRP_MAX - 1)

#endif /* __PRP_LINK_H */
